Document: mongo-cxx-driver-legacy
Title: Debian mongo-cxx-driver-legacy Manual
Author: <insert document author here>
Abstract: This manual describes what mongo-cxx-driver-legacy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mongo-cxx-driver-legacy/mongo-cxx-driver-legacy.sgml.gz

Format: postscript
Files: /usr/share/doc/mongo-cxx-driver-legacy/mongo-cxx-driver-legacy.ps.gz

Format: text
Files: /usr/share/doc/mongo-cxx-driver-legacy/mongo-cxx-driver-legacy.text.gz

Format: HTML
Index: /usr/share/doc/mongo-cxx-driver-legacy/html/index.html
Files: /usr/share/doc/mongo-cxx-driver-legacy/html/*.html
